### PR TITLE
support android

### PR DESCRIPTION
**Pull request by linsui**
I test it on Fenix and at least the basic function works now.

### CODE REVIEW

**Comment by sblask** [comment]
Cool stuff, didn't know about optional chaining. Before this change, did it not work at all, or did it work while printing an error in the console?

**Comment by linsui** [comment]
Before this change it didn't work at all on Android.

**Comment by crssi** [comment]
This looks interesting.
What is the meaning of `?`?
Can you share URL to more info about it? 

Thank you
Cheers

**Comment by linsui** [comment]
> What is the meaning of ??
> Can you share URL to more info about it?

https://javascript.info/optional-chaining

**Comment by crssi** [comment]
Thank you @sblask ❤️

**Comment by sblask** [comment]
This has now been submitted.

**Comment by linsui** [comment]
Thanks! It works!

**Comment by sblask** [comment]
@linsui where did you get the update from? I just got an email from someone saying they can't find it on the addon page? I don't use Firefox on Android, is there anything special going on?

**Comment by linsui** [comment]
The official Firefox for Android only support few addons in stable channel. Firefox Nightly, iceraven and Fennec F-Droid can install addons from a custom collection.

**Pull request merged**
